//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        internal object productdetail;

        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string SupplierID { get; set; }
        public string CatagoryID { get; set; }
        public string QualityPerUnit { get; set; }
        public string UnitPrice { get; set; }
    }
}
